[build]
  publish = "dist"
  command = "npm run build"
  functions = "functions"

[[plugins]]
package = "@netlify/plugin-local-install-core"

[[plugins]]
package = "/plugin/netlify-plugin-diy-analytics"
